name: Build Docs
on:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Fetch Docs âœ¨
        run: |
          git submodule update --init --recursive
          git config --local user.email "avi.grg4567@gmail.com"
          git config --local user.name "avisionx"
          git submodule update --recursive --remote
          git add .
          git commit -m "update docs âœ”ï¸" || echo "No changes to commit"
      - name: Push changes ğŸ¥‚
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
